### ISSUE TITLE
Suggestion: Support for units/commodities

### ISSUE THREAD

**Issue by whereswaldon** [howeyc/ledger#10]
Unless I'm doing something very wrong, this implementation of ledger does not seem to support USD as a commodity.

If this is the case, I would suggest prioritizing this, as it stops anyone interested in tracking more than one currency (or cryptocurrency) from using this implementation. Depending on the scale of change required, I might be interested in helping with it.

Regardless, this is an awesome project. Keep up the good work, even if these features don't make it into your backlog!

**Comment by aThorp96** [comment]
I really support this. Tracking my accounts and cryptocurrencies in one place is one of the biggest reasons I started using ledger to begin with.

**Comment by howeyc** [comment]
You are correct. I support "numbers" only. There is no "commodity" or "unit" or "currency" functionality.

I myself handle multiple currencies with accounts and an intermediary accounts that "convert" between them and hold the gains and losses.

I myself will likely not add it because I don't need it.

I kind of support such functionality for reporting purposes. You can match an account with a stock or unit of coins for looking at a portfolio. Only on the web command/view though.


Having said all that, I welcome pull requests. So feel free to give it a shot.

**Comment by whereswaldon** [comment]
@howeyc Could you explain how your intermediary accounts work in more detail? If there is a straightforward alternative, I'd like to know how it's done.

**Comment by howeyc** [comment]
I'm not sure about straightforward, but it "works for me."

Here's a recent transaction to illustrate how I would convert 800 CAD to 653 USD in my two bank accounts, TD Bank is USD, PC Financial is CAD, Currency Exchange is the difference (gain/loss):

```
2017/09/14 Transfer to USA
    Assets:Current Assets:TD Bank                            653.07
    Assets:Current Assets:PC Financial           -800
    Expenses:Bank Service Charge:Service Charges         7.92
    Income:Other Income:Currency Exchange
```

I realize this simplicity may not work for others, especially with currencies much further apart in value, or you want to know the total assets current value in a particular currency given current exchange rates or something.

If I had to do something myself I'd probably handle it in a report of some kind, where I assigned each account a currency and then fetched current exchange rates when displaying the report or something.

**Comment by gorilax** [comment]
Met my friends, once I told them bout the Bulgarian MiningNow project, that I invested in. Said it`d show itself, but the guys didn`t believe me. And tonight I took my phone and showed them the news that MNW and the industrial company RUSAL are now partners in the field of digital technologies: http://www.4-traders.com/UNITED-COMPANY-RUSAL-PLC-6165909/news/United -Rusal-RUSAL-sets-up-the-infrastructure-for-data-center-at-NAZ-25591032 /? Utm_medium = RSS & utm_content = 20171130! You should have seen their faces!

**Comment by howeyc** [comment]
@aThorp96 Regarding your cryptocurrency comment, I would recommend you look at the "lweb" program, the [sample-portfolio](https://github.com/howeyc/ledger/blob/master/cmd/lweb/portfolio-sample.toml) configuration file. It may suit your needs.

Of course if you'd rather have everything strictly command line and need support in the ledger file itself, go for it.

**Comment by howeyc** [comment]
This has been open for well over a year and I haven't done it, so it seems very likely I'm not going to do it. Contributions are welcome though.
