### ISSUE TITLE
Suggestion: Use `dep` as dependency management tool?

### ISSUE THREAD

**Issue by whereswaldon** [howeyc/ledger#11]
Ledger currently vendors its dependencies, but I imagine that managing the contents of that vendor directory can be a pain, especially if you want to experiment with different dependency versions.

The Go community at large seems to finally be converging on a tool to manage this nightmare: [dep](https://github.com/golang/dep). I've been using it for a little while in some of my other projects, and I think that it's a nice addition to any Go project.

The chief value proposition for this project would be making simple edits to the Gopkg.toml to update all of the vendored dependency versions. You could even choose to remove the vendor directory from the repo completely, since `dep` makes building that vendor directory deterministic.

Of course, I don't even know if this is a pain point for you @howeyc. If not, please disregard.

**Comment by howeyc** [comment]
Yes. I will do that.

I've used a few different vendor tools over the life of this project. I think gb and gvt. I'll switch to dep.

I will always vendor and commit. I've seen too many dependencies disappear (google code for example), vendor is the only way forward for me.
