### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by pedroalbanese** [howeyc/ledger#21]
$ go build -ldflags=-s .
parse.go:12:2: use of internal package github.com/howeyc/ledger/internal/github.com/joyt/godate not allowed

How do proceed?

**Comment by pedroalbanese** [comment]
Now I managed to compile. Tell me, is it not possible to read standard input? My journal is encrypted, it's in a cloud, I always decrypt and pass it to the program via pipes. I really need this function. Can you help me?

**Comment by howeyc** [comment]
Give the latest commit a try.

**Comment by pedroalbanese** [comment]
Sorry, I did not understand. Is it possible to do?

**Comment by howeyc** [comment]
Yes, I just made a change, pull down the latest and recompile.

git pull origin master

**Comment by pedroalbanese** [comment]
Nice, thank you very much!!!
