### ISSUE TITLE
New (-f -) function issue

### ISSUE THREAD

**Issue by pedroalbanese** [howeyc/ledger#22]
Hi again,

I'm getting an error when I pass the journal via stdin, it says: "Unable to parse date: include".

Thanks in advance.

**Comment by howeyc** [comment]
the parser only accepts "include" directives if the source is a file. If it's from stdin, shouldn't all transactions come from stdin?

Otherwise just use files.

**Comment by pedroalbanese** [comment]
But if I include the include parameter in another file, I cannot count the entries in my encrypted journal..

I have part of the transactions encrypted, and another part in CSV. The CSV files are automatically converted to a single file whenever I check the balance (limport/convert), but they remain in CSV (they are shared/editable among my partners). The fact is that I decrypt the encrypted file to stdin, passing it to the program, but it does not contain the transactions converted to ledger format automatically, so I need the include param calling the file JointCSV.ledger. The include param must be on the encrypted journal, otherwise I cannot obtain the totals.

I'm goldsmith (not programmer). We use ledger (C++) abourt 3 years, and I'm really decided to change to LedgerGO (by compatibility and simplicity), but I depend on some features and the approving of my partners (we deal with gold, each transaction has a UUID and digital signature). Ledger in GO is really fantastic and I'm trying to convince my partners to adopt it as standard of ur financial tracking system.

**Comment by howeyc** [comment]
I'm really not sure what you are trying to accomplish here. Can't you just temporarily decrypt and put all transactions into one file (to run reports) and the remove the one file once you are done, everything is separate as usual?

So for example, to do what you are doing to decrypt, like "decrypt-stuff file.enc | ledger -f -" becomes 
decrypt-stuff file.enc > mystuff.plain
limport csv-stuff >> mystuff.plain
ledger -f mystuff.plain bal

when done, delete mystuff.plain

Also, I'm not sure what you mean by UUID and signature, if you have extra lines in there my tool may not handle it. My file format is much simpler and has fewer features than the C++ version. This is a deliberate choice on my part.

**Comment by pedroalbanese** [comment]
I understand. My intention is to simplify too. UUID and digital signature was just to illustrate the need to maintain CSV files and not delete them after conversion. I was not referring to the program's functionality. But in this case, you can still add comments with a semicolon.

I just thought that the problem with the include parameter was a bug, not a choice. In this case, it is even possible to pass the journal through stdin, however limitedly (not with all functions), it does not help much. If it is possible to correct just that, I am very grateful.

Yes, it is perfectly possible to decrypt and then calculate, but it is not the safest method and I would have to do it on other people's machines.

Thanks.

**Comment by howeyc** [comment]
Can you use cat, without having any include directives? Everything should be able to come through stdin this way.

For example, assuming decrypt and then csvledger.dat

decrypt mysecretstuff.enc | cat - csvledger.dat | ledger -f - bal

**Comment by pedroalbanese** [comment]
This helps a lot! Thank you!

Man, your program is almost perfect, I have just some problems with automation and some temporary solutions to get around some of them. It is a tip if you are going to improve the code. Improvements and tips on how to get around them are very welcome as well.

In order of importance: (he most important are the unsolved ones, of course, very simple ones)

#1
-j -J functions (for plotting) very simple.
Workaround: (ledger reg | awk "{print $ 1, $ 4}" or "$ 5" repectively, but the accounts and payees cannot contain spaces).

#two
-b "last year", "last # months" expressions (for plotting), for dynamic value based on current date.
Workaround: [date "+% Y /% m /% d" | awk -F "/" "{$ 1 = ($ 1 == 1)? 1: $ 1-1} 1" OFS = "/"]

# 3
limport "note field" parsing to simicolon line. very simple.

# 4
Scape character to add comments to journal file, suppressed on print report (not semicolon equivalent), as you sayd is a choice, but is necessary

# 5
"and not <account>" argument to suppress some subaccount at balance report
The workaround is to sum all the subaccounts, except the one you want to omit (which makes things difficult when the number of accounts fluctuates)

# 6
Pass just total amount to stdout "-F% (total)" equivalent
Workaround: (awk | tail)

Thank u once again!

**Comment by howeyc** [comment]
Those are some interesting ideas, but I'm probably not going to do any of them.

Although 3 sounds interesting, I may do that. But likely not.

As for 4, you could strip it yourself?
For instance your hidden comment could be ";#hidden comment"
cat myfile.ledger | ledger -f - print | sed '/^;#.*/d'

**Comment by pedroalbanese** [comment]
Competence you have. Think calmly, this will not increase the complexity of your code. It will remain simple, but even more functional.

And only 1 and 3, I would be very grateful if I could pay for it. What do you think?

**Comment by pedroalbanese** [comment]
Nice trick (#4).

**Comment by pedroalbanese** [comment]
Thanks for the improve 3. Perfect!

**Comment by howeyc** [comment]
This awk should work for number 1:

ledger reg | awk '{ print $1, $NF}'
ledger reg | awk '{ print $1, $(NF-1)}'

**Comment by pedroalbanese** [comment]
Perfect man, thank you so much for the tips.

I have one last question. Exploring the code, I saw which lines were added, so I'm trying to add the "uuid" field, like the note field (enthusiast). I tryed to repeat:

	var dateColumn, payeeColumn, amountColumn, commentColumn, uuidColumn int
	dateColumn, payeeColumn, amountColumn, commentColumn, uuidColumn = -1, -1, -1, -1, -1

			// UUID
			if uuidColumn >= 0 && record[uuidColumn] != "" {
				trans.Comments = []string{";" + record[uuidColumn]}
			}

But the output shows just one or another field. Is possible explain how to print 2 commentColumn?

**Comment by howeyc** [comment]
> Perfect man, thank you so much for the tips.
> 
> I have one last question. Exploring the code, I saw which lines were added, so I'm trying to add the "uuid" field, like the note field (enthusiast). I tryed to repeat:
> 
> ```
> var dateColumn, payeeColumn, amountColumn, commentColumn, uuidColumn int
> dateColumn, payeeColumn, amountColumn, commentColumn, uuidColumn = -1, -1, -1, -1, -1
> 
> 		// UUID
> 		if uuidColumn >= 0 && record[uuidColumn] != "" {
> 			trans.Comments = append(trans.Comments, ";" + record[uuidColumn])
> 		}
> ```
> 
> But the output shows just one or another field. Is possible explain how to print 2 commentColumn (2 lines with ;)?

adjust as above and make the same adjustment for commentColumn as well

**Comment by pedroalbanese** [comment]
Where? commentColumn appears only in these 2 places .. can you tell me the line?

var dateColumn, payeeColumn, amountColumn, commentColumn, uuidColumn int
dateColumn, payeeColumn, amountColumn, commentColumn, uuidColumn = -1, -1, -1, -1, -1

		} else if strings.Contains(fieldName, "uuid") {
			uuidColumn = fieldIndex

		// UUID
		if uuidColumn >= 0 && record[uuidColumn] != "" {
			trans.Comments = append(trans.Comments, ";" + record[uuidColumn])
		}

I made the 3 adjustments, but the output always show just 1 line of comment..

**Comment by howeyc** [comment]
your lines

`
		// Comment
		if commentColumn >= 0 && record[commentColumn] != "" {
			trans.Comments = []string{";" + record[commentColumn]}
		}
		// UUID
		if uuidColumn >= 0 && record[uuidColumn] != "" {
			trans.Comments = []string{";" + record[uuidColumn]}
		}
`
new lines
`
		// Comment
		if commentColumn >= 0 && record[commentColumn] != "" {
			trans.Comments = append(trans.Comments, ";" + record[commentColumn])
		}
		// UUID
		if uuidColumn >= 0 && record[uuidColumn] != "" {
			trans.Comments = append(trans.Comments, ";" + record[uuidColumn])
		}
`

**Comment by pedroalbanese** [comment]
Very nice man! Now your code meets all my needs. Big thanks! Congratulations on the project, thanks for sharing.

**Comment by pedroalbanese** [comment]
One issue and a tip (I believe it is simple to do and does not increase the complexity of the code):

# 7 (Issue)
limport "target account alias" parameter
The target account always seaches by "Expense", this makes it impossible for me to convert CSV containing Incomes .. To deal with this problem I'll have to recompile the code 7 times changing only the term "Expense" to "Income", "Assets", etc. limportass.exe, limportinc.exe, limportinp.exe (inputs), limportmat.exe (material), limportprod.exe (products), etc. 6 executables in addition to the original, what would disturb the portability (I will run it on my Android too); I believe it's no dificult pass this term as optional param substitucting the default search, when necessary. To make the use of limport less restricted. 

# 8 (Tip)
as:
-payee string
      Filter output to payees that contain this string.

an equivalent:
-comment string
      Filter output to "commentlines" that contain this string. 

To enable the use of tags, now so easy.


(I thought it better to put it here than open another topic. Sorry to be back so soon. Take your time.)

Thanks!

**Comment by pedroalbanese** [comment]
Yeah, now it's perfect! Great work man. Big thanks!
