### ISSUE TITLE
Equity command

### ISSUE THREAD

**Issue by pedroalbanese** [howeyc/ledger#29]
Greetings !! Is there any possibility of implementing the equity command, to archive the old journals?

Thanks in advance.

**Comment by pedroalbanese** [comment]
Thank You very much!!

Can you teach me how to apply the patch in the old version on my mirror? It's just that I stuck in the version whose tools are compiled separately, because I can't compile lweb on Windows. With this version I can compile, on Windows, the binary for my Android. 
https://github.com/pedroalbanese/ledger

A separate tool would not be bad. In short, how would be print.go isolated to be in the same folder as printEquity.go, like the other tools, to compile equity.exe?

Thanks!

**Comment by howeyc** [comment]
No, but I did build a new release that includes the equity command. Depending on the CPU type of your android, just pick the right Linux build.

**Comment by pedroalbanese** [comment]
It worked like this:

<pre>
package main

import (
	"math/big"
	"sort"
	"time"
	"flag"
	"fmt"
	"io"
	"os"
	"github.com/howeyc/ledger"
)


func main() {

	var ledgerFileName string
	flag.StringVar(&ledgerFileName, "f", "", "Ledger file name (*Required).")
	flag.IntVar(&columnWidth, "columns", 79, "Set a column width for output.")
	flag.Parse()

var lreader io.Reader

	if ledgerFileName == "-" {
		lreader = os.Stdin
	} else {
		ledgerFileReader, err := ledger.NewLedgerReader(ledgerFileName)
		if err != nil {
			fmt.Println(err)
			return
		}
		lreader = ledgerFileReader
	}

	generalLedger, parseError := ledger.ParseLedger(lreader)
	if parseError != nil {
		fmt.Printf("%s\n", parseError.Error())
		return
	}

	var trans ledger.Transaction
	trans.Payee = "Opening Balances"
	trans.Date = time.Now()
	if len(generalLedger) > 0 {
		trans.Date = generalLedger[len(generalLedger)-1].Date
	}

	balances := make(map[string]*big.Rat)
	for _, trans := range generalLedger {
		for _, accChange := range trans.AccountChanges {
			if ratNum, ok := balances[accChange.Name]; !ok {
				balances[accChange.Name] = new(big.Rat).Set(accChange.Balance)
			} else {
				ratNum.Add(ratNum, accChange.Balance)
			}
		}
	}

	ratZero := big.NewRat(0, 1)
	for name, bal := range balances {
		if bal.Cmp(ratZero) != 0 {
			trans.AccountChanges = append(trans.AccountChanges, ledger.Account{
				Name:    name,
				Balance: bal,
			})
		}
	}

	sort.Slice(trans.AccountChanges, func(i, j int) bool {
		return trans.AccountChanges[i].Name < trans.AccountChanges[j].Name
	})

	PrintTransaction(&trans, columnWidth)
}
</pre>

Thank You !!
