### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by porjo** [howeyc/ledger#31]
I've noticed a couple of issues while using Ledger:
1. Specifying an invalid `--period` results in hung process. e.g. `./ledger balance --period blah -f ledger.dat` 
2. When filtering transactions using `--payee` the results are those where the transaction description contains the keyword, not the payee (the account into which money was paid). Should `--payee` be renamed to `--description`?

Thanks for your time.

**Comment by howeyc** [comment]
Thanks for the heads up on `--period`

As far as **payee**, that is the same as description. Where the amounts go is **accounts**. You can filter by accounts by specifying additional filters at the end of the command. The filters are just substring/contains matches, and are or'd together.

For example to see the balances of accounts with the word "food" or "online" or "utilities" you can do 

`./ledger -f ledger.dat bal food online utilities`

Similar to examples here:
http://howeyc.github.io/ledger/02_Register.html

**Comment by porjo** [comment]
Thanks for the advice on filtering by accounts.
