### ISSUE TITLE
Import matching existing transactions

### ISSUE THREAD

**Issue by porjo** [howeyc/ledger#35]
While importing, I've noticed that if I have two transactions on the same day where payee starts with the same word, only one of them is imported. I can see from the code that it does a simple match against the first word of the payee field. It would be good to improve that e.g use Bayesian classifier on payee string, or simple match on the first 2-3 words?

**Comment by howeyc** [comment]
Yeah, I have that for when I import credit card transactions. When downloading "current transactions" a few days apart I may get transactions I already imported before. That check is to keep from importing the same transaction twice.

You can use the `--allow-matching` flag to import transactions without doing this check.

**Comment by porjo** [comment]
I can see that ``--allow-matching` would be the solution if it were a situation where multiple identical transactions were being made on the same day. In my case however the only common element is the first word - the remaining payee string and amounts are different. Would you consider extending the simple match to consider first and second word (if it exists)? In my case, that solves the issue.

**Comment by howeyc** [comment]
I think I'm going to change it to do a full payee match, the whole string.
