### ISSUE TITLE
Request: move decimal package out of internal

### ISSUE THREAD

**Issue by whereswaldon** [howeyc/ledger#40]
The fact that `decimal` is in a internal directory means it's impossible for application code in consuming projects to construct `*ledger.Transaction`s at runtime (except by parsing a string representation of them). This makes it hard to build a tool capable of authoring new transactions. Is there a reason that decimal must live in internal?

Regardless, thanks for the great work on this package!

**Comment by howeyc** [comment]
That's a good point I didn't think about. I made it internal because it's not "general purpose" and quite specific for use within ledger.

You're right though, it should be available enough to be used if anyone wants to interface with the ledger package.
