### ISSUE TITLE
Wishlist: Read Only option on Web Ledger

### ISSUE THREAD

**Issue by verkaro** [howeyc/ledger#46]
I enjoy being able to glance at balances via ledger web. But would it be nice in the future to update via the cli and have no access to edit via the browser. This way ledger web functions with **multi-user** read-only access with reasonable security and accountability reserved as git only editable.

**Comment by howeyc** [comment]
I like this idea.

I added a -read-only option when running the web command. It removes the add transaction page.

**Comment by verkaro** [comment]
$ ledger web -read-only -f ledgerRoot.dat
2023/04/25 00:38:06 Listening on port 8056
2023/04/25 00:38:06 open ead-only: no such file or directory
2023/04/25 00:38:06 invalid argument

I installed via: go install github.com/howeyc/ledger/ledger@latest
go version go1.20.1 linux/amd64

I am probably doing something wrong
