### ISSUE TITLE
Sc and ledger

### ISSUE THREAD

**Issue by gedw99** [howeyc/ledger#47]
Hey @howeyc 

i noticed there is an sc and this ledger repo.

for an open science system I need a self hosted sc system but ledger looks also pretty good.

I am Building a gui using gio not Fyne on top . That’s the plan .

would someone be able to tell me if:
Sc can do functions like google sheets where you essentially end up with parametrics. In other words a cell changes and it’s func run that changes other cells. Basically turtle all the way down or up ( I am Australian so down :) 

I ask because I can be the parametrics in to sc or ledger using an event WAL style thing. Basically changes are events and consumers listen to events. Hooks on cells then run their func and create new events etc.. 

thanks and I hope to extend sc and ledge also

**Comment by howeyc** [comment]
It has been a while since I did anything to sc, but yes it keeps back references in the code for any dependent cells. So changing a cell will "bubble up" results and calculations to cells that reference what was changed.

**Comment by gedw99** [comment]
thanks thats what i was looking for.

will let you know when i get the gui working if your interested.
